API_ID = "XXXXXXXX"
API_HASH = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
BOT_TOKEN = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

# Google API Key
GOOGLE_API_KEY = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
MODEL_NAME = "gemini-1.5-flash"
MONGO_URI = "mongodb+srv://tetakaliyamini:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX@cluster0.a0dx6.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
DB_NAME = "TelegramBotDB"
GOOGLE_CSE_ID = "XXXXXXXXXXXXXXXXXXXX"
